// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3ixlpHf8EKYbOn3FQOm9-N4BkUwMwb4',
    appId: '1:379405071350:web:cf39aaa3eba8d424698dd7',
    messagingSenderId: '379405071350',
    projectId: 'store-c1f1d',
    authDomain: 'store-c1f1d.firebaseapp.com',
    storageBucket: 'store-c1f1d.appspot.com',
    measurementId: 'G-SMJ9R7KB91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqfIPzoCf5wZ2-00gSJEEhjs3JxapgocI',
    appId: '1:379405071350:android:70fd87169bd0a5c7698dd7',
    messagingSenderId: '379405071350',
    projectId: 'store-c1f1d',
    storageBucket: 'store-c1f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfX3y9RQ1c7mPe8Sd2MIQrnyLnEMd9tfE',
    appId: '1:379405071350:ios:a5fc991fe29e04d4698dd7',
    messagingSenderId: '379405071350',
    projectId: 'store-c1f1d',
    storageBucket: 'store-c1f1d.appspot.com',
    iosClientId: '379405071350-bgb84ihqv8ehhfbf6q34hh9sbga40qol.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfX3y9RQ1c7mPe8Sd2MIQrnyLnEMd9tfE',
    appId: '1:379405071350:ios:975d9b364004bf49698dd7',
    messagingSenderId: '379405071350',
    projectId: 'store-c1f1d',
    storageBucket: 'store-c1f1d.appspot.com',
    iosClientId: '379405071350-csnmajjosgbdtjkva6d4sj69v51euq7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.store.RunnerTests',
  );
}
